### ISSUE TITLE
Please help me with this.

### ISSUE THREAD

**Issue by maxx166** [lu-wo/DETRtime#4]
How to get train_no_neg1.npz  files,Do you have a way to get  the eeg to npz？

**Comment by lu-wo** [comment]
Hi! We made the prepared files for all paradigms publicly available here: [https://osf.io/ktv7m/](https://osf.io/ktv7m/)
You can find the files in the "segmentation" directory.

I changed the filenames to the default, i.e. "train.npz", thanks for pointing this out!

Let me know if you have further questions.

**Comment by maxx166** [comment]
Thank you for your reply,my questions has been solved.
